import os
import time
print ("THIS PROGRAM IS FOR MAC AND LINUX-IF YOU HAVE WINDOWS THEN OPEN THE FILE...")
time.sleep(0.1)
print ("ScrollingText.py")
print ("program starting in 5")
time.sleep(1)
print ("program starting in 4")
time.sleep(1)
print ("program starting in 3")
time.sleep(1)
print ("program starting in 2")
time.sleep(1)
print ("program starting in 1")
time.sleep(1)
print ("program starting in 0")
time.sleep(2)

os.system('clear')
print ("S")
time.sleep(0.1)
os.system('clear')
print ("Sc")
time.sleep(0.1)
os.system('clear')
print ("Scr")
time.sleep(0.1)
os.system('clear')
print ("Scrol")
time.sleep(0.1)
os.system('clear')
print ("Scroll")
time.sleep(0.1)
os.system('clear')
print ("Scrolli")
time.sleep(0.1)
os.system('clear')
print ("Scrollin")
time.sleep(0.1)
os.system('clear')
print ("Scrolling")
time.sleep(0.1)
os.system('clear')
print ("Scrolling ")
time.sleep(0.1)
os.system('clear')
print ("Scrolling T")
time.sleep(0.1)
os.system('clear')
print ("Scrolling Te")
time.sleep(0.1)
os.system('clear')
print ("Scrolling Tex")
time.sleep(0.1)
os.system('cl')
print ("Scrolling Text")
time.sleep(2)
print ("")
time.sleep(0.1)
print ("")
time.sleep(0.1)
print ("Thank You For Using")
time.sleep(0.1)
print ("blapplejuice's")
time.sleep(0.1)
print ("Python")
time.sleep(0.1)
print ("Scrolling")
time.sleep(0.1)
print ("Text")
time.sleep(0.1)
print ("Demo!")
time.sleep(5)

